version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    targets:
      - windows_amd64_v1
      - linux_amd64_v1
      - darwin_arm64
upx:
  - enabled: true
    goos: [windows, linux]
    compress: best
    lzma: true
snapshot:
  version_template: "SNAPSHOT-{{ .ShortCommit }}"
archives:
  - files:
      - LICENSE
      - README.md
      - templates/*
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: async-lab
    name: AsyncReverseProxy
  replace_existing_artifacts: true
  prerelease: auto
