[[remotes]]
name = "server1"
address = "localhost:8080"
token = "qwhrqwh"

[[remotes]]
name = "server2"
address = "localhost:8081"
token = "qwhrqwh"


[[proxies]]
name = "proxy1"
proto = "tcp"
remotes = ["server1", "server2"]
backend = "localhost:80"
frontend = "localhost:54321"
priority = 0                     # bigger is higher priority
weight = 1

[[proxies]]
name = "proxy2"
proto = "tcp"
remotes = ["server1"]
backend = "localhost:3000"
frontend = "localhost:54322"
priority = 0
weight = 1


# You can use the same config for another client, 
# then you can realize ha and load balancing.
