name: snapshot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    concurrency:
      group: snapshot
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make upx
          VERSION="$(<VERSION)"
          git tag "$VERSION"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
